### ISSUE TITLE
mkvenv error

### ISSUE THREAD

**Issue by GerBreOwn** [solovyevn/pyvenvwrapper#2]
I have been using pyvenvwrapper for awhile.  

Now when I run mkvenv I get the following error: "WARNING: the pyenv script is deprecated in favour of `python3.6 -m venv` Error: Command '['/home/medrec2/.virtualenvs/projects/simonproj/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1"

Is there any way to get around this error?  Or is there a newer version that eliminates this error? Or do I have to use Python3.5 instead of 3.6?

Thanks.

**Comment by solovyevn** [comment]
Hello and thanks for using the tool!

Unfortunately, I didn't have a time to update the tool for newer versions of python, where `pyvenv` command is deprecated and calling it leads to an error, that you've shown.

One solution is to keep using the pyvenvwrapper with [virtualenv](https://pypi.org/project/virtualenv/) instead of `pyvenv`:
- Install the virtualenv by running `pip install virtualenv` in global site-packages (when NO venv is activated).
- Now you can make your virtual environments by running `mkvenv` with `-u` option, i.e. if usually you do `mkvenv %your_env_name%`, now it should be `mkvenv -u 'virtualenv' %your_env_name%`.
- Other features should work as before.

Also, you can eliminate providing `-u` option every time by providing no choice for the tool, but to fallback to `virtualenv`, by removing the `pyvenv` script completely. To remove the `pyvenv` script, which is deprecated anyway and gives that error, run `sudo rm "$(which pyvenv)"` (when NO venv is activated).
After this is done, you can do `mkvenv %your_env_name%` as before, because pyvenvwrapper will choose virtualenv now by itself.

**Comment by solovyevn** [comment]
Hello @GerBreOwn,

I have updated the pyvenvwrapper tool to 1.0.0 version, it now supports virtual environment creation using `venv` directly, and also has a new option to `mkvenv` command, that allows to specify which Python executable to use for new virtual environment.

Regarding the error, that you have provided... If it will happen again when using version 1.0.0 of pyvenvwrapper, then it's not an issue with `pyvenv` vs `venv`. I found out, that this error `Error: Command '['/home/medrec2/.virtualenvs/projects/simonproj/bin/python3.6', '-Im', 'ensurepip', '--upgrade', '--default-pip']' returned non-zero exit status 1` may occur on systems missing `ensurepip` module. (If you would execute this command directly it will provide you with a more descriptive error, stating that `ensurepip` module is missing). For example, this can be the case when using Python from Anaconda, because it doesn't provide this module, or a system package is missing from your Linux installation.
Options to solve the issue:
- Try installing `python*-venv` module on your system, e.g. `sudo apt-get install python3-venv`, `sudo apt-get install python3.6-venv`, etc.
- Tell `pyvenv`/`venv` to make a virtual environment without `pip` installation, but tell `pyvenvwrapper` to install `pip` for you, just run `mkvenv -o '--without-pip' --pip %your_env_name%`. This way the error won't happen, because the underlying `venv` tool won't try to use `ensurepip` and will create a new virtual environment without `pip`. But right after it is created `pyvenvwrapper` itself will check that `pip` is missing inside the new virtual environment and install it using PyPA's `get-pip.py` script.
